# coding: utf-8
x = linspace(0, 2*pi, 50)
plot(x, sin(x))
x[0]
x[49]
xlabel('x')
ylable('sin(x)')
xlabel('x')
xlabel(`x`)
clf()
y = linspace(0,2*pi,50)
plot(y,sin(2*y))
xlabel('y')
ylabel('sin(2y)')
get_ipython().magic('run "c:\\users\\lenovo\\appdata\\local\\temp\\tmpg_rcxa.py"')
title('Sinusoids')
legend(['sin(2y)'])
legend(['sin(2y)'],loc='center')
plot(y,cos(y),'r')
clf()
plot(y,sin(y),'g',linewidth=2)
annotate('local max',xy=(1.5,1))
savefig('sin.png')
close()
y = linspace(0,2*pi,50)
clf()
plot(y,sin(y))
plot(y,cos(y))
xlabel('y')
ylabel('f(y)')
legend(['sin(y)','cos(y)'])
clf()
figure(1)
plot(y,sin(y))
figure(2)
plot(y,cos(y))
savefig('cosine.png')
figure(1)
title('sin(y)')
savefig('sine.png')
close()
close()
xmin,xmax=xlim()
ymin,ymax=ylim()
print(xmin,xmax)
xlim(xmin,2*pi)
ylim(ymin-0.2,ymax+0.2)
get_ipython().magic('pinfo plot')
get_ipython().magic('pinfo2 plot')
0
plot(-x,cos(-x))
plot(x,cos(x))
clf()
x = linspace(-5*pi,5*pi)
plot(x,sin(x))
plot(x,xsin(x))
xmin,xmax=xlim()
xlim(xmin,5*pi)
ylim(ymin-15,ymax+15)
annotate('origin',xy=(0,0))
x = linspace(15,15)
plot(x)
x = linspace(0,15)
plot(x)
y = linspace(0,15)
x = linspace(0,15)
plot(x,y)
x = linspace(-15,15)
y = linspace(-15,15)
plot(x,y)
y = linspace(15,-15)
x = linspace(15,-15)
plot(x,y)
clf()
x = linspace(-5*pi,5*pi)
clf()
xmin,xmax=xlim()
xlim(xmin,5*pi)
ylim(ymin-15,ymax+15)
annotate('origin',xy=(0,0))
y = linspace(0,5*pi)
x = linspace(0,5*pi)
plot(x,sin(x),'g')
plot(x,sin(2*x),'g')
clf()
xmin,xmax=xlim()
xlim(xmin,5*pi)
ylim(ymin-15,ymax+15)
annotate('origin',xy=(0,0))
x = linspace(0,5*pi)
plot(x,sin(2*x),'g')
clf()
x = linspace(-5*pi,5*pi,500)
plot(x,x,'b')
plot(x,-x,'b')
plot(x,sin(x),'g',linewidth=2)
plot(x,x*sin(x),'r',linewidth=3)
get_ipython().magic('hist')
get_ipython().magic('save four.py 1 -20')
