import numpy as np
print(np.random.seed(27))
data = np.random.normal(loc=10,scale=2,size=1000)
print(np.percentile(data,50))
print(np.median(data))
print(np.percentile(data,[25,50,75]))
data1 = np.random.randint(0,100,size=5)
print(data1)
print(np.random.shuffle(data1))
print(np.random.permutation(10))
print(np.random.permutation(5))
print(np.random.permutation(data1))
data2 = np.random.permutatiom(5)
print(data2)
print(np.random.choice(data2))
